version: "2.3"
services:
  web:
    build: .
    image: mydotnetdev
    ports:
      - "5000:5000"
      - "5001:5001"
    ipc: host
    container_name: corerestweb
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password22"
        ACCEPT_EULA: "Y"
